theme = "slick"
icons = "awesome"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = false
speed_up = false
speed_down = false
graph_up = false
interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "time"
interval = 60
format = "%m-%d %T"
